name = "phoenix_hexapod"
description = "Phoenyx Hexapod"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded"]

project-files = ["gnat/arduino.gpr"]

[configuration]
#disabled = true

[[depends-on]]
a0b_armv7m_systick_clock = "*"
a0b_atsam3x8e_tc5_timer = "*"
#a0b_callbacks = "*"
#a0b_i2c = "~0.1.0-dev"
#a0b_svd_stm32h723 = "*"
#a0b_time = "*"
#a0b_timer = "*"
a0b_tasking = "*"
light_arduino_due = "*"

a0b_gpio = "*"

[[pins]]
a0b_armv7m = { path='subprojects/a0b-armv7m' }
#a0b_armv7m_systick_clock = { path='subprojects/a0b-armv7m-systick_clock' }
a0b_atsam3x8e = { path='subprojects/a0b-atsam3x8e' }
#a0b_atsam3x8e_tc5_timer = { path='subprojects/a0b-atsam3x8e-tc5_timer' }
##a0b_armv7m_systick_clock_timer = { path='../a0b-armv7m-systick_clock_timer' }
a0b_base = { path='subprojects/a0b-base' }
a0b_callbacks = { path='subprojects/a0b-callbacks' }
#a0b_svd_stm32h723 = { path='../a0b-svd-stm32h723' }
a0b_tasking = { path='subprojects/a0b-tasking' }
a0b_time = { path='subprojects/a0b-time' }
a0b_timer = { path='subprojects/a0b-timer' }
#a0b_i2c = { path='../a0b-i2c' }
