name = "phoenix_hexapod_blackpill_stm32f401"
description = "Phoenyx Hexapod Firmware for BlackPill STM32F401"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded"]

project-files = ["../gnat/blackpill_stm32f401.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[configuration.values]
a0b_armv7m.fpu_extension = "VFPv4"
cgk.Float_Size = "32"

[[depends-on]]
a0b_armv7m_systick_clock = "*"
a0b_pca9685 = "*"
a0b_playstation2_controller = "*"
a0b_stm32f401_gpio = "*"
a0b_stm32f401_i2c = "*"
a0b_stm32f401_tim11_timer = "*"
a0b_stm32f401_usart = "*"
a0b_tasking = "*"
cgk = "*"
light_blackpill_stm32f401 = "*"

[[pins]]
a0b_armv7m = { path='../subprojects/a0b-armv7m' }
a0b_base = { path='../subprojects/a0b-base' }
a0b_callbacks = { path='../subprojects/a0b-callbacks' }
a0b_exti = { path='../subprojects/a0b-exti' }
a0b_gpio = { path='../subprojects/a0b-gpio' }
a0b_i2c = { path='../subprojects/a0b-i2c' }
a0b_pca9685 = { path='../subprojects/a0b-pca9685' }
a0b_playstation2_controller = { path='../subprojects/a0b-playstation2_controller' }
a0b_spi = { path='../subprojects/a0b-spi' }
a0b_stm32f401_dma = { path='../subprojects/a0b-stm32f401-dma' }
a0b_stm32f401_gpio = { path='../subprojects/a0b-stm32f401-gpio' }
a0b_stm32f401_i2c = { path='../subprojects/a0b-stm32f401-i2c' }
a0b_stm32f401_usart = { path='../subprojects/a0b-stm32f401-usart' }
a0b_tasking = { path='../subprojects/a0b-tasking' }
a0b_time = { path='../subprojects/a0b-time' }
a0b_timer = { path='../subprojects/a0b-timer' }
cgk = { path='../subprojects/cgk' }
light_blackpill_stm32f401 = { path='../subprojects/light-startup/blackpill_stm32f401' }
